author: leelawd93
database: false
description: Logs chat and commands
main: net.moddedminecraft.mmclogger.MMCLogger
name: MMCLogger
startup: postworld
version: 1.3
permissions:
  mmclogger.notify:
    description: Players with this permission get notified when a player says anything on the chat or command notify list.
    default: op
  mmclogger.exempt:
    description: Players with this permission do not get logged for anything.
    default: false
commands:
  clog:
    description: This is a base command for many MMCLogger commands.
    usage: /<command>
    permission: mmclogger.command
    permission-message: You don't have permission to use this command!
